Sample of NAXAM xamarin forms app which has a runtime failure.
```
Java.Lang.NoClassDefFoundError:

Failed resolution of: Lcom/mapbox/services/android/telemetry/location/LostLocationEngine;
```